exams/urls.py
from django.conf.urls import url,include
from .views import (ExamMarkListView,
                    ExamMarkCreateView,
                    ExamMarkDetailView,
                    ExamMarkUpdateView,
                    ExamMarkDeleteView,
                    
                    )
    

urlpatterns = [
    
    url(r'^(?P<pk>\d+)/$',ExamMarkDetailView.as_view(),name="exams-detail"),
    url(r'^list/$', ExamMarkListView.as_view(),name="examlist"),
    url(r'^create/$',ExamMarkCreateView.as_view(),name="addmark"),
    url(r'^(?P<pk>[\w-]+)/$',ExamMarkUpdateView.as_view(),name="updatem"),
    url(r'^(?P<pk>[\w-]+)/update/$',ExamMarkUpdateView.as_view(),name="update"),
    url(r'^(?P<pk>[\w-]+)/delete/$',ExamMarkDeleteView.as_view(),name="delete-mark",)
    
    
    
]

fees/urls.py
from django.conf.urls import url,include
from .views import (FeesListView,
                    FeesCreateView,
                    FeesDetailView,
                    FeesUpdateView,
                    FeesDeleteView,
                    
                    )
    

urlpatterns = [
    
    url(r'^(?P<pk>\d+)/$',FeesDetailView.as_view(),name="fees-detail"),
    url(r'^list/$', FeesListView.as_view(),name="feeslist"),
    url(r'^create/$',FeesCreateView.as_view(),name="addfees"),
    url(r'^(?P<pk>[\w-]+)/update/$',FeesUpdateView.as_view(),name="update"),
    url(r'^(?P<pk>[\w-]+)/delete/$',FeesDeleteView.as_view(),name="delete-fee",)
    
    
    
]

hostels/urls.py
from django.conf.urls import url,include
from .views import (HostelListView,
                    HostelCreateView,
                    HostelDetailView,
                    HostelUpdateView,
                    HostelDeleteView,
                    
                    )
    

urlpatterns = [
    
    url(r'^(?P<pk>\d+)/$',HostelDetailView.as_view(),name="hostel-detail"),
    url(r'^list/$', HostelListView.as_view(),name="hostellist"),
    url(r'^create/$',HostelCreateView.as_view(),name="addhostel"),
    url(r'^(?P<pk>[\w-]+)/$',HostelUpdateView.as_view(),name="updatem"),
    url(r'^(?P<pk>[\w-]+)/update/$',HostelUpdateView.as_view(),name="update-hostel"),
    url(r'^(?P<pk>[\w-]+)/delete/$',HostelDeleteView.as_view(),name="delete-hostel",)
    
    
    
]

library/urls.py
from django.conf.urls import url,include
from .views import (BookListView,
                    BorrowingListView,
                    BookCreateView,
                    BorrowingCreateView,
                    DetailView,
                    BorrowingUpdateView,
                    BorrowingDeleteView,
                    BookDeleteView,
                    BookUpdateView,
                    
                    )
    

urlpatterns = [
    
    
    url(r'^list/$', BookListView.as_view(),name="booklist"),
    url(r'^list/borrow/$', BorrowingListView.as_view(),name="borrowlist"),
    url(r'^create/book/$',BookCreateView.as_view(),name="addbook"),
    url(r'^(?P<pk>[\w-]+)/$',BookUpdateView.as_view(),name="updatebook"),
    url(r'^create/borrow/$',BorrowingCreateView.as_view(),name="addborrowing"),
    url(r'^(?P<pk>[\w-]+)/update/borrowing/$',BorrowingUpdateView.as_view(),name="updateborrow"),
    url(r'^(?P<pk>[\w-]+)/$',BookUpdateView.as_view(),name="updateborrowing"),
    url(r'^(?P<pk>[\w-]+)/update/book/$',BookUpdateView.as_view(),name="updatebook"),
    url(r'^(?P<pk>[\w-]+)/delete/book/$',BookDeleteView.as_view(),name="delete-book"),
    url(r'^(?P<pk>[\w-]+)/delete/borrowing/$',BorrowingDeleteView.as_view(),name="delete-borrow",)
    
    
    
]

parents/urls.py
from .views import StudentListView,TeacherListView,BookListView,BorrowingListView,FeeListView

from django.conf.urls import url

urlpatterns = [
    url(r'^student/$', StudentListView.as_view(),name="student"),
    url(r'^teacher/$', TeacherListView.as_view(),name="teacher"),
    url(r'^payment/$', FeeListView.as_view(),name="payment"),
    url(r'^books/$', BookListView.as_view(),name="books"),
    url(r'^borrowings/$', BorrowingListView.as_view(),name="borrowing"), 

]

report/urls.py
from django.urls import reverse_lazy
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetView,
    PasswordChangeView,
    PasswordResetDoneView,
    PasswordChangeDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView
    )
from profiles.views import ProfileFollowToggle, RegisterView,activate_user_view
from exams.views import HomeView
from django.views.generic import TemplateView



urlpatterns = [
    
    url(r'^admin/', admin.site.urls),
    url(r'^home/$',HomeView.as_view(),name="home"),
    url(r'^about/$',TemplateView.as_view(template_name='about.html'),name="about"),
    url(r'^$',LoginView.as_view(), name="login"),
    url(r'^contact/$',TemplateView.as_view(template_name='contact.html'),name="contact"),
    url(r'^exams/', include('exams.urls',namespace="exams")),
    url(r'^attendance/', include('attendance.urls',namespace="attendance")),
    url(r'^coursework/', include('coursework.urls',namespace="coursework")),
    url(r'^students/', include('students.urls',namespace="students")),
    url(r'^reports/', include('reports.urls',namespace="reports")),
    url(r'^fees/', include('fees.urls',namespace="fees")),
    url(r'^hostels/', include('hostels.urls',namespace="hostels")),
    url(r'^library/', include('library.urls',namespace="library")),
     url(r'^parents/', include('parents.urls',namespace="parents")),
    url(r'^login/$',LoginView.as_view(), name="login"),
    url(r'^logout/$',LogoutView.as_view(), name="logout"),
    url(r'^activate/(?P<code>[a-z0-9].*)/$',activate_user_view, name='activate'),
    url(r'^register/$',RegisterView.as_view(), name="register"),
    url(r'^profile-follow/$',ProfileFollowToggle.as_view(),name="follow"),
    url(r'^u/', include('profiles.urls',namespace="profiles")),
    url(r'^password_change/$',PasswordChangeView.as_view(template_name='registration/password_change_form.html'),name='password_change'),
    url(r'^password_change/done/$',PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'),name='password_change_done'),
    url(r'^password_reset/$',PasswordResetView.as_view(template_name='registration/password_reset_form.html'),name='password_reset'),
    url(r'^password_reset/done/$',PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'),name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',PasswordResetConfirmView.as_view(
        template_name='accounts/password_reset_confirm.html'),name='password_reset_confirm'),
    url(r'^reset/done/$',PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),name='password_reset_complete'), 
    
    
        
        
        
    
    
    
]

templates/snippets/form_snippets.html
{% extends "change_form.html"%}
{%block head_title%} Add Subjects ||{{block.super}}{%endblock head_title%}

{%block content %}
<h1> {{title}}</h1>
{%if form.errors.non_field_errors %}
{{form.errors.non_field_errors}}
{% endif %}

<form method="POST">
<fieldset class="module aligned wide">
{% csrf_token %}
<!--Student Number:</br><input name="student_number" type="text"></br>
Subject_ID:</br><input name="subject_ID" type="text"></br>
 Mark: </br><input name="Total_Mark" type="text"></br>-->
 {{form.as_p}}
 <center>
<input type="submit" value="add">
</center>

</form>
<fieldset>
{%endblock %}

templates/snippets/nav.html
{% if user.is_authenticated and user.is_teacher %}



<li><a href='{%url "register" %}'>register </a></li>
<li><a href='{%url "exams:addmark" %}'>Add Exam Marks </a></li></li>
<li><a href='{%url "coursework:addcontinuous" %}'>Add Coursework </a></li>
<li><a href='{%url "reports:addreport" %}'>Add Reports </a></li>
<li><a href='{%url "exams:examlist" %}'>View Examination Marks </a></li>
<li><a href='{%url "coursework:listcontinuous" %}'>View Coursework </a></li>

<li><a href='{%url "profiles:profilelist" %}'>View Users </a></li>
<li><a href='{%url "reports:reportlist" %}'>View Reports </a></li>


<li><a href='{%url "password_change" %}'>Change Password </a></li>




{% else %}
{% if user.is_authenticated and user.is_student%}
<li><a href='{%url "students:exammark" %}'>View Examinations Results </a></li>
<li><a href='{%url "students:studentscontinuous" %}'>View Coursework  </a></li>
<li><a href='{%url "students:fees" %}'>View Fees  </a></li>
<li><a href='{%url "students:hostels" %}'>View Accomodation  </a></li>
<li><a href='{%url "students:borrowing" %}'>View Library Information  </a></li>
<li><a href='{%url "students:reportst" %}'>View Report </a></li>

{% else %}
{% if user.is_authenticated and user.is_admin %}
<li><a href='{%url "parents:student" %}'>View Students </a></li>
<li><a href='{%url "parents:teacher" %}'>View Teachers </a></li>
<li><a href='{%url "parents:books" %}'>View school books </a></li>
<li><a href='{%url "parents:payment" %}'>View student payments </a></li>
<li><a href='{%url "parents:borrowing" %}'>View Library Information </a></li>

<li><a href='{%url "register" %}'>Register </a></li>
<li><a href='{%url "password_change" %}'>Change Password </a></li>\

{% else %}
{% if user.is_authenticated and user.is_librarian %}
<li><a href='{%url "library:booklist" %}'>View Books </a></li>
<li><a href='{%url "library:addbook" %}'>Add Books </a></li>
<li><a href='{%url "library:borrowlist" %}'>View Borrowing list </a></li>
<li><a href='{%url "library:addborrowing" %}'>Add Borrowing entry</a></li>
<li><a href='{%url "password_change" %}'>Change Password </a></li>
{% else %}
{% if user.is_authenticated and user.is_Burser %}
<li><a href='{%url "fees:feeslist" %}'>Payments List </a></li>
<li><a href='{%url "fees:addfees" %}'>Make Payment </a></li>
<li><a href='{%url "password_change" %}'>Change Password </a></li>
{% else %}
{% if user.is_authenticated and user.is_secretary %}
<li><a href='{%url "hostels:hostellist" %}'>Accomodation Information </a></li>
<li><a href='{%url "hostels:addhostel" %}'>Add Student Accomodation </a></li>
<li><a href='{%url "password_change" %}'>Change Password </a></li>


{% endif %}
{% endif %}
{% endif %}
{% endif %}
{% endif %}
{% endif %}



</div>