fees/urls.py
from django.conf.urls import url,include
from .views import (FeesListView,
                    FeesCreateView,
                    FeesDetailView,
                    FeesUpdateView,
                    FeesDeleteView,
                    
                    )
    

urlpatterns = [
    
    url(r'^(?P<pk>\d+)/$',FeesDetailView.as_view(),name="fees-detail"),
    url(r'^list/$', FeesListView.as_view(),name="feeslist"),
    url(r'^create/$',FeesCreateView.as_view(),name="addfees"),
    url(r'^(?P<pk>[\w-]+)/update/$',FeesUpdateView.as_view(),name="update"),
    url(r'^(?P<pk>[\w-]+)/delete/$',FeesDeleteView.as_view(),name="delete-fee",)
    
    
    
]

parents/urls.py
from .views import StudentListView,TeacherListView,BookListView,BorrowingListView,FeeListView

from django.conf.urls import url

urlpatterns = [
    url(r'^student/$', StudentListView.as_view(),name="student"),
    url(r'^teacher/$', TeacherListView.as_view(),name="teacher"),
    url(r'^payment/$', FeeListView.as_view(),name="payment"),
    url(r'^books/$', BookListView.as_view(),name="books"),
    url(r'^borrowings/$', BorrowingListView.as_view(),name="borrowing"), 

]

profiles/urls.py
from .views import ProfileDetailView,ProfileListView,ProfileDeleteView,ProfileUpdateView,StudentListView

from django.conf.urls import url

urlpatterns = [
    url(r'^list/$', ProfileListView.as_view(),name="profilelist"), 
    url(r'^(?P<pk>[\w-]+)/delete/$',ProfileDeleteView.as_view(),name="delete-user",),
    url(r'^(?P<pk>[\w-]+)/update/$',ProfileUpdateView.as_view(),name="update"),
    url(r'^student/$', StudentListView.as_view(),name="student"),
  

]

report/urls.py
from django.urls import reverse_lazy
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetView,
    PasswordChangeView,
    PasswordResetDoneView,
    PasswordChangeDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView
    )
from profiles.views import ProfileFollowToggle, RegisterView,activate_user_view
from exams.views import HomeView
from django.views.generic import TemplateView



urlpatterns = [
    
    url(r'^admin/', admin.site.urls),
    url(r'^home/$',HomeView.as_view(),name="home"),
    url(r'^about/$',TemplateView.as_view(template_name='about.html'),name="about"),
    url(r'^$',LoginView.as_view(), name="login"),
    url(r'^contact/$',TemplateView.as_view(template_name='contact.html'),name="contact"),
    url(r'^exams/', include('exams.urls',namespace="exams")),
    url(r'^attendance/', include('attendance.urls',namespace="attendance")),
    url(r'^coursework/', include('coursework.urls',namespace="coursework")),
    url(r'^students/', include('students.urls',namespace="students")),
    url(r'^reports/', include('reports.urls',namespace="reports")),
    url(r'^fees/', include('fees.urls',namespace="fees")),
    url(r'^hostels/', include('hostels.urls',namespace="hostels")),
    url(r'^library/', include('library.urls',namespace="library")),
     url(r'^parents/', include('parents.urls',namespace="parents")),
    url(r'^login/$',LoginView.as_view(), name="login"),
    url(r'^logout/$',LogoutView.as_view(), name="logout"),
    url(r'^activate/(?P<code>[a-z0-9].*)/$',activate_user_view, name='activate'),
    url(r'^register/$',RegisterView.as_view(), name="register"),
    url(r'^profile-follow/$',ProfileFollowToggle.as_view(),name="follow"),
    url(r'^u/', include('profiles.urls',namespace="profiles")),
    url(r'^password_change/$',PasswordChangeView.as_view(template_name='registration/password_change_form.html'),name='password_change'),
    url(r'^password_change/done/$',PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'),name='password_change_done'),
    url(r'^password_reset/$',PasswordResetView.as_view(template_name='registration/password_reset_form.html'),name='password_reset'),
    url(r'^password_reset/done/$',PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'),name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',PasswordResetConfirmView.as_view(
        template_name='accounts/password_reset_confirm.html'),name='password_reset_confirm'),
    url(r'^reset/done/$',PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),name='password_reset_complete'), 
    
    
        
        
        
    
    
    
]

parents/models.py
from django.db import models

# Create your models here.

parents/views.py
from django.shortcuts import render
from django.shortcuts import render
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from exams.models import ExamMark
from coursework.models import Continuous_Assessment
from attendance.models import Attendance
from reports.models import Reports
from fees.models import Fee
from profiles.models import Profile
from library.models import Borrowing,Book
from hostels.models import Hostel
from django.db.models import Q
from django.views.generic import ListView,DetailView,CreateView,UpdateView,View
from django.contrib.auth.models import User

class HomeView(View):
    def get(self,request,*args,**kwargs):
        if not request.user.is_authenticated():
            return render(request, "home.html",{})
        user=request.user
        
        is_following_user_ids=[x.user.id for x in user.is_following.all()]
        qs=Continuous_Assessment.objects.filter(user__id__in=is_following_user_ids).order_by("student_number")[:5]
        for x in user.is_following.all():
            return render(request, "continuous/home-feed.html",{"object_list":qs})
    
    

#class Continuous_AssessmentListView(LoginRequiredMixin,ListView):
   
  # template_name="students/continuous_assessment_list.html"
   #model=Continuous_Assessment
   
   #def get_context_data(self,*args,**kwargs):
        #user=self.request.user
        
        #taken=super(Continuous_AssessmentListView, self).get_context_data(*args,**kwargs)
        #taken['locations'] =Continuous_Assessment.objects.filter(student_number=user)
        #return taken
class StudentListView(ListView,LoginRequiredMixin):
    template_name='parents/students_list.html'
    def get_queryset(self):
        return Profile.objects.filter(school=self.request.user).filter(is_student=True)
class TeacherListView(ListView,LoginRequiredMixin):
    template_name='parents/teachers_list.html'
    def get_queryset(self):
        return Profile.objects.filter(school=self.request.user).filter(is_teacher=True)
class FeeListView(ListView,LoginRequiredMixin):
    template_name='parents/fees_list.html'
    def get_queryset(self):
        return Fee.objects.filter(school=self.request.user)
class BookListView(ListView,LoginRequiredMixin):
    template_name='parents/bookis_list.html'
    def get_queryset(self):
        return Book.objects.filter(school=self.request.user)
class BorrowingListView(ListView,LoginRequiredMixin):
    template_name='parents/borrowings_list.html'
    def get_queryset(self):
        return Borrowing.objects.filter(school=self.request.user)  




# Create your views here.

parents/templates/parents/bookis_list.html
{% extends "tables.html"%}

{%block head_title%} Library system||{{block.super}}{%endblock head_title%}



{%block content %}


 <div class="right_col" role="main">
          <div class="">
            <div class="page-title">
              <div class="title_left">
                <h3> Library System</h3>
              </div>

              
            </div>

            <div class="clearfix"></div>

            <div class="row">
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    
                    <div class="clearfix"></div>
                  </div>
                 
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    
                    <div class="clearfix"></div>
                  </div>
                  

              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    
                    <div class="clearfix"></div>
                  </div>
                 
                    <table id="datatable-buttons" class="table table-striped table-bordered">
                      <thead>
                        <tr>
                         <th >Book number</th>
                         <th>Date Published</th>
                         <th>Author</th>
                         <th>Book Title </th>
                        
                        </tr>
                      </thead>
                   

                      <tbody>
					  {% for obj in object_list %}
                        <tr>
                          <td>{{obj.book_number}}</a></td>
                          <td>{{obj.published_date}}</td>
                          <td>{{obj.Author}}</td>
                          <td>{{obj.book_title}}</td>
                          
                        </tr>
                        {%endfor%}
                        
                      </tbody>
					  
                    </table>
                  </div>
                </div>
              </div>
			  </div>
			  </div>
			   </div>
			    </div>
			  {%endblock content%}

             

parents/templates/parents/borrowings_list.html
{% extends "tables.html"%}

{%block head_title%} Library Information ||{{block.super}}{%endblock head_title%}



{%block content %}


 <div class="right_col" role="main">
          <div class="">
            <div class="page-title">
              <div class="title_left">
                <h3>Library Information</h3>
              </div>

              
            </div>

            <div class="clearfix"></div>

            <div class="row">
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    
                    <div class="clearfix"></div>
                  </div>
                 
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    
                    <div class="clearfix"></div>
                  </div>
                  

              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    
                    <div class="clearfix"></div>
                  </div>
                 
                    <table id="datatable-buttons" class="table table-striped table-bordered">
                      <thead>
                        <tr>
						<th> student number </th>
                         <th>Book Number</th>
                         <th>Book Title</th>
                         <th>Date Taken</th>
                         <th>Return Date </th>
                        </tr>
                      </thead>
                

                      <tbody>
					     {% for obj in object_list %}
                        <tr>
                          <td>{{obj.student_number}}</a></td>
                          <td>{{obj.book_number}}</td>
                          <td>{{obj.book_title}}</td>
                          <td>{{obj.date_taken}}</td>
                          <td>{{obj.return_date}}</td>

                        </tr>
                          {%endfor%}
                        
                      </tbody>
					
                    </table>
                  </div>
                </div>
              </div>
			  </div>
			  </div>
			   </div>
			    </div>
			  {%endblock content%}

             

parents/templates/parents/delete_user.html
{% extends "base_site.html"%}
{%block head_title%}Delete ExamMark||{{block.super}}{%endblock head_title%}


{%block content %}

{%if form.errors.non_field_errors %}
{{form.errors.non_field_errors}}
{% endif %}


<div id="content-main">
<form method="POST">
<fieldset class="module aligned wide">

{% csrf_token %}


<p> do you want to delete {{object.username}}</p>

 
 <center>
<input type="submit" name='submit' value="delete"></br>
</center>


</form>

</div>
</fieldset>
{%endblock %}

parents/templates/parents/detail-update.html
{% extends "base_site.html"%}
{%block head_title%} {{form.instance.username}} ||{{block.super}}{%endblock head_title%}



{%block content %}
<h2>{{object.username}} </h2>

<hr/>
<h3> make changes </h3>
{%include 'snippets/form_snippets.html' with form=form%}
{%endblock content%}

parents/templates/parents/fees_list.html
{% extends "tables.html"%}

{%block head_title%}Payment History||{{block.super}}{%endblock head_title%}



{%block content %}


 <div class="right_col" role="main">
          <div class="">
            <div class="page-title">
              <div class="title_left">
                <h3>Payment History</h3>
              </div>

              
            </div>

            <div class="clearfix"></div>

            <div class="row">
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    
                    <div class="clearfix"></div>
                  </div>
                 
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    
                    <div class="clearfix"></div>
                  </div>
                  

              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    
                    <div class="clearfix"></div>
                  </div>
                 
                    <table id="datatable-buttons" class="table table-striped table-bordered">
                      <thead>
                        <tr>
                         <th>student number</th>
                         <th>Invoice number</th>
                         <th>Amount paid</th>
                         <th>Tutoring Fee</th>
                         <th>Bank name </th>
                         
                        </tr>
                      </thead>
                   

                      <tbody>
					  {% for obj in object_list %}
                        <tr>
                          <td>{{obj.student_number}}</td>
                          <td>{{obj.invoice_number}}</td>
                          <td>{{obj.Amount_paid}}</td>
                          <td>{{obj.tutoring_fee}}</td>
                          <td>{{obj.Bank_name}}</td>
                        </tr>
                        {%endfor%}
                        
                      </tbody>
					  
                    </table>
                  </div>
                </div>
              </div>
			  </div>
			  </div>
			   </div>
			    </div>
			  {%endblock content%}

             

parents/templates/parents/profile_list.html
{% extends "tables.html"%}

{%block head_title%} Examination Results ||{{block.super}}{%endblock head_title%}



{%block content %}


 <div class="right_col" role="main">
          <div class="">
            <div class="page-title">
              <div class="title_left">
                <h3>Students list</h3>
              </div>

              
            </div>

            <div class="clearfix"></div>

            <div class="row">
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    
                    <div class="clearfix"></div>
                  </div>
                 
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    
                    <div class="clearfix"></div>
                  </div>
                  

              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    
                    <div class="clearfix"></div>
                  </div>
                 
                    <table id="datatable-buttons" class="table table-striped table-bordered">
                      <thead>
                        <tr>
                         <th >username</th>
						  <th >name</th>
						   <th>Surname </th>
						    <th >school</th>
							 <th >Delete</th>
                        </tr>
                      </thead>
                  

                      <tbody>
					   {% for obj in object_list %}
                        <tr>
                          <td>{{obj.username}}</td>
						    <td>{{obj.first_name}}</td>
							  <td>{{obj.last_name}}</td>
							    <td>{{obj.school}}</td>
                                <td><a href='{%url "profiles:delete-user" obj.id %}'>delete</a></td>
                        </tr>
                        
                        {%endfor%}
                      </tbody>
					  
                    </table>
                  </div>
                </div>
              </div>
			  </div>
			  </div>
			   </div>
			    </div>
			  {%endblock content%}

             

parents/templates/parents/students_list.html
{% extends "tables.html"%}

{%block head_title%} Examination Results ||{{block.super}}{%endblock head_title%}



{%block content %}


 <div class="right_col" role="main">
          <div class="">
            <div class="page-title">
              <div class="title_left">
                <h3>Student List</h3>
              </div>

              
            </div>

            <div class="clearfix"></div>

            <div class="row">
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    
                    <div class="clearfix"></div>
                  </div>
                 
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    
                    <div class="clearfix"></div>
                  </div>
                  

              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    
                    <div class="clearfix"></div>
                  </div>
                 
                    <table id="datatable-buttons" class="table table-striped table-bordered">
                      <thead>
                        <tr>
                         <th >username</th>
						  <th >name</th>
						   <th>Surname </th>
						    <th >school</th>
                        </tr>
                      </thead>
                   

                      <tbody>
					  {% for obj in object_list %}
                        <tr>
                          <td>{{obj.username}}</td>
						    <td>{{obj.first_name}}</td>
							  <td>{{obj.last_name}}</td>
							    <td>{{obj.school}}</td>
                        </tr>
                        {%endfor%}
                        
                      </tbody>
					  
                    </table>
                  </div>
                </div>
              </div>
			  </div>
			  </div>
			   </div>
			    </div>
			  {%endblock content%}

             

parents/templates/parents/teachers_list.html
{% extends "tables.html"%}

{%block head_title%} Examination Results System ||{{block.super}}{%endblock head_title%}



{%block content %}


 <div class="right_col" role="main">
          <div class="">
            <div class="page-title">
              <div class="title_left">
                <h3>Teacher List</h3>
              </div>

              
            </div>

            <div class="clearfix"></div>

            <div class="row">
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    
                    <div class="clearfix"></div>
                  </div>
                 
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    
                    <div class="clearfix"></div>
                  </div>
                  

              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    
                    <div class="clearfix"></div>
                  </div>
                 
                    <table id="datatable-buttons" class="table table-striped table-bordered">
                      <thead>
                        <tr>
                        <th >username</th>
						  <th >name</th>
						   <th>Surname </th>
						    <th >school</th>
                        </tr>
                      </thead>
                

                      <tbody>
					     {% for obj in object_list %}
                        <tr>
                          <td>{{obj.username}}</td>
						    <td>{{obj.first_name}}</td>
							  <td>{{obj.last_name}}</td>
							    <td>{{obj.school}}</td>
                        </tr>
                          {%endfor%}
                        
                      </tbody>
					
                    </table>
                  </div>
                </div>
              </div>
			  </div>
			  </div>
			   </div>
			    </div>
			  {%endblock content%}

             

parents/templates/parents/user.html
{% extends "base.html"%}
{%block head_title%} {{user.username}} ||{{block.super}}{%endblock head_title%}



{%block content %}
<h2> {{user.username}}</h2>
<p>{% include 'profiles/snippets/follow_form.html' with username=user.username is_following=is_following%}</p>
<form method="GET" action=".">
<input type="text" placeholder="search..." name="q" value={{request.GET.q}}>
<button type="submit">search</button>
</form>
</hr>


<h2> {{user.username}}</h2>
{%if locations %}


<table border="1">
<th> studentnumber</th>
<th>subject_ID</th>
<th>paper1_Mark</th>
<th>paper2_Mark</th>
<th>paper3_Mark</th>
<th>paper4_Mark</th>
{% for rest in locations%}

<tr>
<td><a href='{{request.path}}?q={{rest.student_number}}'>{{rest.student_number}}</a></td>
<td>{{rest.subject_ID}}</td>
<td>{{rest.paper1_Mark}}</td>
<td>{{rest.paper2_Mark}}</td>
<td>{{rest.paper3_Mark}}</td>
<td>{{rest.paper4_Mark}}</td>
</tr>
{%endfor%}
<a href='{{request.path}}?q={{ing}}'></a>


</table>
{% else%}
<p><strong>No items Found</strong></p>

{%endif%}
{%endblock content%}