exams/urls.py
from django.conf.urls import url,include
from .views import (ExamMarkListView,
                    ExamMarkCreateView,
                    ExamMarkDetailView,
                    ExamMarkUpdateView,
                    ExamMarkDeleteView,
                    
                    )
    

urlpatterns = [
    
    url(r'^(?P<pk>\d+)/$',ExamMarkDetailView.as_view(),name="exams-detail"),
    url(r'^list/$', ExamMarkListView.as_view(),name="examlist"),
    url(r'^create/$',ExamMarkCreateView.as_view(),name="addmark"),
    url(r'^(?P<pk>[\w-]+)/$',ExamMarkUpdateView.as_view(),name="updatem"),
    url(r'^(?P<pk>[\w-]+)/update/$',ExamMarkUpdateView.as_view(),name="update"),
    url(r'^(?P<pk>[\w-]+)/delete/$',ExamMarkDeleteView.as_view(),name="delete-mark",)
    
    
    
]

fees/urls.py
from django.conf.urls import url,include
from .views import (FeesListView,
                    FeesCreateView,
                    FeesDetailView,
                    FeesUpdateView,
                    FeesDeleteView,
                    
                    )
    

urlpatterns = [
    
    url(r'^(?P<pk>\d+)/$',FeesDetailView.as_view(),name="fees-detail"),
    url(r'^list/$', FeesListView.as_view(),name="feeslist"),
    url(r'^create/$',FeesCreateView.as_view(),name="addfees"),
    url(r'^(?P<pk>[\w-]+)/update/$',FeesUpdateView.as_view(),name="update"),
    url(r'^(?P<pk>[\w-]+)/delete/$',FeesDeleteView.as_view(),name="delete-fee",)
    
    
    
]

payment/urls.py
from django.conf.urls import url,include
from .views import (PaymentListView,
                    PaymentCreateView,
                    PaymentDetailView,
                    PaymentUpdateView,
                    PayementDeleteView,
                    
                    )
    

urlpatterns = [
    
    url(r'^(?P<pk>\d+)/$',PaymentDetailView.as_view(),name="fees-detail"),
    url(r'^list/$', PaymentListView.as_view(),name="feeslist"),
    url(r'^create/$',PaymentCreateView.as_view(),name="addfees"),
    url(r'^(?P<pk>[\w-]+)/update/$',PaymentUpdateView.as_view(),name="update"),
    url(r'^(?P<pk>[\w-]+)/delete/$',PaymentDeleteView.as_view(),name="delete-fee",)
    
    
    
]

report/urls.py
from django.urls import reverse_lazy
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetView,
    PasswordChangeView,
    PasswordResetDoneView,
    PasswordChangeDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView
    )
from profiles.views import ProfileFollowToggle, RegisterView,activate_user_view
from exams.views import HomeView
from django.views.generic import TemplateView



urlpatterns = [
    
    url(r'^admin/', admin.site.urls),
    url(r'^home/$',HomeView.as_view(),name="home"),
    url(r'^about/$',TemplateView.as_view(template_name='about.html'),name="about"),
    url(r'^$',LoginView.as_view(), name="login"),
    url(r'^contact/$',TemplateView.as_view(template_name='contact.html'),name="contact"),
    url(r'^exams/', include('exams.urls',namespace="exams")),
    url(r'^attendance/', include('attendance.urls',namespace="attendance")),
    url(r'^coursework/', include('coursework.urls',namespace="coursework")),
    url(r'^students/', include('students.urls',namespace="students")),
    url(r'^reports/', include('reports.urls',namespace="reports")),
    url(r'^fees/', include('fees.urls',namespace="fees")),
    url(r'^hostels/', include('hostels.urls',namespace="hostels")),
    url(r'^library/', include('library.urls',namespace="library")),
     url(r'^parents/', include('parents.urls',namespace="parents")),
    url(r'^login/$',LoginView.as_view(), name="login"),
    url(r'^logout/$',LogoutView.as_view(), name="logout"),
    url(r'^activate/(?P<code>[a-z0-9].*)/$',activate_user_view, name='activate'),
    url(r'^register/$',RegisterView.as_view(), name="register"),
    url(r'^profile-follow/$',ProfileFollowToggle.as_view(),name="follow"),
    url(r'^u/', include('profiles.urls',namespace="profiles")),
    url(r'^password_change/$',PasswordChangeView.as_view(template_name='registration/password_change_form.html'),name='password_change'),
    url(r'^password_change/done/$',PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'),name='password_change_done'),
    url(r'^password_reset/$',PasswordResetView.as_view(template_name='registration/password_reset_form.html'),name='password_reset'),
    url(r'^password_reset/done/$',PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'),name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',PasswordResetConfirmView.as_view(
        template_name='accounts/password_reset_confirm.html'),name='password_reset_confirm'),
    url(r'^reset/done/$',PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),name='password_reset_complete'), 
    
    
        
        
        
    
    
    
]

reports/urls.py
from django.conf.urls import url,include
from .views import (ReportsListView,
                    ReportsCreateView,
                    ReportsDeleteView,
                    ReportsUpdateView,
                    ReportsDetailView,
                    
                    )
    

urlpatterns = [
    
    url(r'^(?P<pk>\d+)/$',ReportsDetailView.as_view(),name="detail"),
    url(r'^list/$', ReportsListView.as_view(),name="reportlist"),
    url(r'^create/$',ReportsCreateView.as_view(),name="addreport"),
    url(r'^(?P<pk>[\w-]+)/delete/$',ReportsDeleteView.as_view(),name="delete",),
    url(r'^(?P<pk>[\w-]+)/update/$',ReportsUpdateView.as_view(),name="update",)
    
    
    
    
]

fees/models.py
from django.db import models
from django.conf import settings
from django.core.urlresolvers import reverse
from django.db.models import Q
User=settings.AUTH_USER_MODEL
class Fee(models.Model):
    user=models.ForeignKey(User)
    school=models.CharField(max_length=50)
    Amount_paid=models.DecimalField(max_digits=5, decimal_places=2)
    student_number=models.CharField(max_length=50)
    invoice_number=models.CharField(max_length=50)
    tutoring_fee=models.DecimalField(max_digits=5, decimal_places=2)
    Bank_name=models.CharField(max_length=50)
    def __str__(self):
        return self.student_number
    def get_absolute_url(self):
        return reverse('fees:detail', kwargs={'pk':self.pk})
    def get_absolute_url(self):
        return reverse('fees:update', kwargs={'pk':self.pk}) 



# Create your models here.

payment/models.py
from django.db import models
class Payment(models.Model):
    school=models.CharField(max_length=50)
    Amount_paid=models.DecimalField(max_digits=5, decimal_places=2)
    student_number=models.CharField(max_length=50)
    invoice_number=models.CharField(max_length=50)
    tutoring_fee=models.DecimalField(max_digits=5, decimal_places=2)
    Bank_name=models.CharField(max_length=50)
    def get_absolute_url(self):
        return reverse('fpayment:detail', kwargs={'pk':self.pk})
    def get_absolute_url(self):
        return reverse('payment:update', kwargs={'pk':self.pk})
    

# Create your models here.

fees/forms.py
from django import forms
from .models import Fee

class   FeesForm(forms.ModelForm):
    class Meta:
        
        model=Fee
        fields=[
            'school',
            'student_number',
            'Amount_paid',
            'invoice_number',
            'tutoring_fee',
            'Bank_name',
             ]
    def __init__(self,user=None,*args,**kwargs):
        #print(kwargs.pop('user'))
        print(user)
        #print(kwargs.pop('instance'))
        super(FeesForm,self).__init__(*args,**kwargs)
         
    

                

payment/forms.py
from django import forms
from .models import Payment

class   PaymentForm(forms.ModelForm):
    class Meta:
        
        model=Payment
        fields=[
            'student_number',
            'Amound_paid',
            'invoice_number',
            'tutoring_fee',
            'Bank_name',
             ]
    def __init__(self,user=None,*args,**kwargs):
        #print(kwargs.pop('user'))
        print(user)
        #print(kwargs.pop('instance'))
        super(PaymentForm,self).__init__(*args,**kwargs)
         
    

                

fees/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import FeesForm
from .models import Fee
from django.urls import reverse
from django.views.generic import ListView,DetailView,CreateView,UpdateView,View,DeleteView


class HomeView(View):
    def get(self,request,*args,**kwargs):
        #if not request.user.is_authenticated():
        return render(request, "exams/home.html",{})
        #user=request.user
        
        #is_following_user_ids=[x.user.id for x in user.is_following.all()]
        #qs=ExamMark.objects.filter(user__id__in=is_following_user_ids).order_by("student_number")[:5]
        #for x in user.is_following.all():
            #return render(request, "teachers/home-feed.html",{"object_list":qs})

class FeesListView(ListView,LoginRequiredMixin):
    def get_queryset(self):
        return Fee.objects.filter(user=self.request.user)
    
 
    
class FeesDetailView(DetailView,LoginRequiredMixin):
    def get_queryset(self):
        return Fee.objects.filter(user=self.request.user)
    
    
class FeesCreateView(LoginRequiredMixin,CreateView):
    form_class=FeesForm
    login_url='/login/'
    template_name="fees/forms.html"
    success_url='/create/'
    def get_queryset(self):
        return Fee.objects.filter(user=self.request.user)
    def get_context_data(self,*args,**kwargs):
        context=super(FeesCreateView,self).get_context_data(*args,**kwargs)
        context['title']='Add Payment'
        return context
    def form_valid(self, form):
        obj=form.save(commit=False)
        obj.user=self.request.user
        return super(FeesCreateView,self).form_valid(form)
    def get_form_kwargs(self):
        kwargs=super(FeesCreateView,self).get_form_kwargs()
        kwargs['user']=self.request.user
        return kwargs
    def get_success_url(self):
        return reverse('fees:addfees')

    
    
class FeesUpdateView(LoginRequiredMixin,UpdateView):
    template_name="fees/update_fees.html"
    form_class=FeesForm
    def get_queryset(self):
        return Fee.objects.filter(user=self.request.user)
    def get_context_data(self,*args,**kwargs):
        context=super(FeesUpdateView,self).get_context_data(*args,**kwargs)
        context['title']='Update Fees'
        return context
    def get_form_kwargs(self):
        kwargs=super(FeesUpdateView,self).get_form_kwargs()
        kwargs['user']=self.request.user
        return kwargs
    def get_success_url(self):
        return reverse('fees:feeslist')
   



class FeesDeleteView(LoginRequiredMixin,DeleteView):
    model=  Fee
    template_name="fees/delete_fees.html"
    form_class=FeesForm
    def get_context_data(self,*args,**kwargs):
        context_data=super(FeesDeleteView,self).get_context_data(*args,**kwargs)
        pk=self.kwargs.get('pk')
        fee=Fee.objects.get(id=int(pk))
        context_data.update({'fee':fee})
        return context_data
    def get_success_url(self):
        return reverse('fees:feeslist')
   






# Create your views here.


# Create your views here.

payment/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import PaymentForm
from .models import Payment
from django.urls import reverse
from django.views.generic import ListView,DetailView,CreateView,UpdateView,View,DeleteView


class HomeView(View):
    def get(self,request,*args,**kwargs):
        #if not request.user.is_authenticated():
        return render(request, "exams/home.html",{})
        #user=request.user
        
        #is_following_user_ids=[x.user.id for x in user.is_following.all()]
        #qs=ExamMark.objects.filter(user__id__in=is_following_user_ids).order_by("student_number")[:5]
        #for x in user.is_following.all():
            #return render(request, "teachers/home-feed.html",{"object_list":qs})

class PaymentListView(ListView,LoginRequiredMixin):
    def get_queryset(self):
        return Payment.objects.filter(user=self.request.user)
    def get_context_data(self,*args,**kwargs):
        context=super(PaymentListView, self).get_context_data(*args,**kwargs)
        query=self.request.GET.get('q')
        qs=Payment.objects.filter(user=self.request.user).search(query)
    
        
            
        if qs.exists():
            context['locations']=qs
        
        return context
 
    
class PaymentDetailView(DetailView,LoginRequiredMixin):
    def get_queryset(self):
        return Payment.objects.filter(user=self.request.user)
    
    
class PaymentCreateView(LoginRequiredMixin,CreateView):
    form_class=FeeForm
    login_url='/login/'
    template_name="payment/forms.html"
    success_url='/create/'
    def get_queryset(self):
        return Payment.objects.filter(user=self.request.user)
    def get_context_data(self,*args,**kwargs):
        context=super(PaymentCreateView,self).get_context_data(*args,**kwargs)
        context['title']='Add Payment'
        return context
    def form_valid(self, form):
        obj=form.save(commit=False)
        obj.user=self.request.user
        return super(PaymentCreateView,self).form_valid(form)
    def get_form_kwargs(self):
        kwargs=super(PaymentCreateView,self).get_form_kwargs()
        kwargs['user']=self.request.user
        return kwargs
    def get_success_url(self):
        return reverse('payment:addfees')

    
    
class PaymentUpdateView(LoginRequiredMixin,UpdateView):
    template_name="payment/update_fees.html"
    form_class=PaymentForm
    def get_queryset(self):
        return Payment.objects.filter(user=self.request.user)
    def get_context_data(self,*args,**kwargs):
        context=super(PaymentUpdateView,self).get_context_data(*args,**kwargs)
        context['title']='Update Fees'
        return context
    def get_form_kwargs(self):
        kwargs=super(PaymentUpdateView,self).get_form_kwargs()
        kwargs['user']=self.request.user
        return kwargs
    def get_success_url(self):
        return reverse('payment:feeslist')
   



class PaymentDeleteView(LoginRequiredMixin,DeleteView):
    model=Payment
    template_name="payment/delete_fees.html"
    form_class=FeesForm
    def get_context_data(self,*args,**kwargs):
        context_data=super(paymentDeleteView,self).get_context_data(*args,**kwargs)
        pk=self.kwargs.get('pk')
        payment=Payment.objects.get(id=int(pk))
        context_data.update({'payment':payment})
        return context_data
    def get_success_url(self):
        return reverse('payment:feeslist')
   






# Create your views here.


# Create your views here.

payment/templates/fees/delete_fees.html
{% extends "base_site.html"%}
{%block head_title%}Delete ExamMark||{{block.super}}{%endblock head_title%}


{%block content %}

{%if form.errors.non_field_errors %}
{{form.errors.non_field_errors}}
{% endif %}


<div id="content-main">
<form method="POST">
<fieldset class="module aligned wide">

{% csrf_token %}


<p> do you want to delete {{object.student_number}}</p>
 
 <center>
<input type="submit" name='submit' value="delete"></br>
</center>


</form>

</div>
</fieldset>
{%endblock %}

payment/templates/fees/fees_list.html
{% extends "tables.html"%}

{%block head_title%} Examination Results ||{{block.super}}{%endblock head_title%}



{%block content %}


 <div class="right_col" role="main">
          <div class="">
            <div class="page-title">
              <div class="title_left">
                <h3>Examination Results</h3>
              </div>

              
            </div>

            <div class="clearfix"></div>

            <div class="row">
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    
                    <div class="clearfix"></div>
                  </div>
                 
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    
                    <div class="clearfix"></div>
                  </div>
                  

              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    
                    <div class="clearfix"></div>
                  </div>
                 
                    <table id="datatable-buttons" class="table table-striped table-bordered">
                      <thead>
                        <tr>
                         <th >student number</th>
                         <th>subject name</th>
                         <th>Total Mark</th>
                         <th>grade</th>
                         <th>comment </th>
                         <th>edit </th>
                         <th>delete</th>
                        </tr>
                      </thead>
                   {% for obj in object_list %}

                      <tbody>
                        <tr>
                          <td>{{obj.student_number}}</a></td>
                          <td>{{obj.subject_name}}</td>
                          <td>{{obj.Total_Mark}}</td>
                          <td>{{obj.grade}}</td>
                          <td>{{obj.comment}}</td>
                          <td><a href='{%url "exams:update" obj.id %}'>edit| </a></td>
                          <td><a href='{%url "exams:delete-mark" obj.id %}'>delete</a></td>
                        </tr>
                        
                        
                      </tbody>
					  {%endfor%}
                    </table>
                  </div>
                </div>
              </div>
			  </div>
			  </div>
			   </div>
			    </div>
			  {%endblock content%}

             

payment/templates/fees/forms.html
{% extends "change_form.html"%}
{%block head_title%} Add Exam Marks ||{{block.super}}{%endblock head_title%}


{%block content %}

{%if form.errors.non_field_errors %}
{{form.errors.non_field_errors}}
{% endif %}


<div id="content-main">
<form method="POST">
<fieldset class="module aligned wide">

{% csrf_token %}


 {{form.as_p}}
 
 <center>
<input type="submit" value="Add"></br>
</center>


</form>

</div>
</fieldset>
{%endblock %}

payment/templates/fees/home-feed.html
{% extends "base.html"%}

{%block content %}
{% for obj in object_list %}
<h1><a href='{% url "profiles:detail" username=obj.user.username %}'>{{obj.user.username}}</a></h1>
{% endfor%}
<table border="1">
<th> studentnumber</th>
<th>subject_ID</th>
<th>paper1_Mark</th>
<th>paper2_Mark</th>
<th>paper3_Mark</th>
<th>paper4_Mark</th>
{% for obj in object_list%}

<tr>
<td><a href='{% url "profiles:detail" username=obj.user.username %}?q={{obj.student_number}}'>{{obj.student_number}}</a></td>
<td>{{obj.subject_ID}}</td>
<td>{{obj.paper1_Mark}}</td>
<td>{{obj.paper2_Mark}}</td>
<td>{{obj.paper3_Mark}}</td>
<td>{{obj.paper4_Mark}}</td>
</tr>

{% endfor%}



</table>





{%endblock content%}

payment/templates/fees/home.html
{% extends "tables.html"%}

{%block head_title%} Examination Results ||{{block.super}}{%endblock head_title%}



{%block content %}


 <div class="right_col" role="main">
          <div class="">
            <div class="page-title">
              <div class="title_left">
                <h2>Welcome {{user.first_name}} {{user.last_name}}</h2>
				<h3> e-brains drive the web</h3>
				
              </div>

              
            </div>

            <div class="clearfix"></div>

            <div class="row">
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    
                    <div class="clearfix"></div>
                  </div>
                 
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    
                    <div class="clearfix"></div>
                  </div>
                  

              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    
                    <div class="clearfix"></div>
                  </div>
                 
                    <table id="datatable-buttons" class="table table-striped table-bordered">
                      <thead>
                        <tr>
                         <th >username</th>
						 <th>Name </th>
						 <th>Surname</th>
						 <th>school</th>
						 
						 
                         
                        </tr>
                      </thead>
                   

                      <tbody>
                        <tr>
                          <td>{{user.username}}</td>
						  <td>{{user.first_name}}</td>
						  <td>{{user.last_name}}</td>
						  <td>{{user.school}}</td>
						  
						  
                          
                        </tr>
                        
                        
                      </tbody>
					  
                    </table>
                  </div>
                </div>
              </div>
			  </div>
			  </div>
			   </div>
			    </div>
			  {%endblock content%}

             

payment/templates/fees/index.html
{% extends "base_site.html" %}
{% load i18n static %}

{% block extrastyle %}{{ block.super }}<link rel="stylesheet" type="text/css" href="{% static "admin/css/dashboard.css" %}" />{% endblock %}

{% block coltype %}colMS{% endblock %}

{% block bodyclass %}{{ block.super }} dashboard{% endblock %}

{% block breadcrumbs %}{% endblock %}

{% block content %}
<div id="content-main">

{% if app_list %}
    {% for app in app_list %}
        <div class="app-{{ app.app_label }} module">
        <table>
        <caption>
            <a href="{{ app.app_url }}" class="section" title="{% blocktrans with name=app.name %}Models in the {{ name }} application{% endblocktrans %}">{{ app.name }}</a>
        </caption>
        {% for model in app.models %}
            <tr class="model-{{ model.object_name|lower }}">
            {% if model.admin_url %}
                <th scope="row"><a href="{{ model.admin_url }}">{{ model.name }}</a></th>
            {% else %}
                <th scope="row">{{ model.name }}</th>
            {% endif %}

            {% if model.add_url %}
                <td><a href="{{ model.add_url }}" class="addlink">{% trans 'Add' %}</a></td>
            {% else %}
                <td>&nbsp;</td>
            {% endif %}

            {% if model.admin_url %}
                <td><a href="{{ model.admin_url }}" class="changelink">{% trans 'Change' %}</a></td>
            {% else %}
                <td>&nbsp;</td>
            {% endif %}
            </tr>
        {% endfor %}
        </table>
        </div>
    {% endfor %}
{% else %}
    <p>{% trans "You don't have permission to edit anything." %}</p>
{% endif %}
</div>
{% endblock %}

{% block sidebar %}
<div id="content-related">
    <div class="module" id="recent-actions-module">
        <h2>{% trans 'Recent actions' %}</h2>
        <h3>{% trans 'My actions' %}</h3>
            {% load log %}
            {% get_admin_log 10 as admin_log for_user user %}
            {% if not admin_log %}
            <p>{% trans 'None available' %}</p>
            {% else %}
            <ul class="actionlist">
            {% for entry in admin_log %}
            <li class="{% if entry.is_addition %}addlink{% endif %}{% if entry.is_change %}changelink{% endif %}{% if entry.is_deletion %}deletelink{% endif %}">
                {% if entry.is_deletion or not entry.get_admin_url %}
                    {{ entry.object_repr }}
                {% else %}
                    <a href="{{ entry.get_admin_url }}">{{ entry.object_repr }}</a>
                {% endif %}
                <br/>
                {% if entry.content_type %}
                    <span class="mini quiet">{% filter capfirst %}{{ entry.content_type }}{% endfilter %}</span>
                {% else %}
                    <span class="mini quiet">{% trans 'Unknown content' %}</span>
                {% endif %}
            </li>
            {% endfor %}
            </ul>
            {% endif %}
    </div>
</div>
{% endblock %}

payment/templates/fees/update_fees.html
{%block content %}
<hr/>
{%include 'snippets/form_snippets.html' with form=form%}
{%endblock content%}